### ISSUE TITLE
Missing parameters in `regulfactTurgor.comp` function definition 

### ISSUE THREAD

**Issue by ecamo19** [NicoINRA/SurEau_V2#3]
Hi Nico!

There are some missing parameters in the definition of the `regulfactTurgor.comp` function

The function is defined as:

```R
regulfactTurgor.comp <- function(Tpress = Tpress, TpRESSUREMax = TpRESSUREMax)
```
however the `Emax` and `Ecuti` are missing. 

I think the definition should be:

```R
regulfactTurgor.comp <- function(Tpress, TpRESSUREMax, Emax, Ecuti)
```
since those are parameters that are required:
 
https://github.com/NicoINRA/SurEau_V2/blob/6c82eae48bce6ac1f7cb0722d8e2ef980f9d9fb1/functions/plant.utils.R#L66-L67

Best;
Erick

**Comment by NicoINRA** [comment]
I come back to you tonight on these prblems.
Nico

URFM, INRAe, Avignon
--


De : Erick Calderón-Morales ***@***.***>
Répondre à : NicoINRA/SurEau_V2 ***@***.***>
Date : mardi 12 décembre 2023 à 06:18
À : NicoINRA/SurEau_V2 ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [NicoINRA/SurEau_V2] Missing parameters in `regulfactTurgor.comp` function definition (Issue #3)


Hi Nico!

There are some missing parameters in the definition of the regulfactTurgor.comp function

The function is defined as:

regulfactTurgor.comp <- function(Tpress = Tpress, TpRESSUREMax = TpRESSUREMax)

however the Emax and Ecuti are missing.

I think the definition should be:

regulfactTurgor.comp <- function(Tpress, TpRESSUREMax, Emax, Ecuti)

since those are parameters that are required:

https://github.com/NicoINRA/SurEau_V2/blob/6c82eae48bce6ac1f7cb0722d8e2ef980f9d9fb1/functions/plant.utils.R#L66-L67

Best;
Erick

**Comment by NicoINRA** [comment]
Dear Erik,

Iam sorry for touching base late. This code you mention is not used anymore in the model. I will remove commit and pushed the modifications on Gitlab.

The code used for regulation is the following, which is located in functionsWBveg.r :


# This function computes regulation ie stomatal closure parameters (including derivative from current psi)
# stomatalclosure is 0, 1 or 2 depending on the value of psi in "PiecewieLinear"
# regulFact is regul proportion between 0 and 1
# regulFactPrime is the first order derivative of regul function in psi
compute.regulFact <- function(psi, params, regulationType) {
  if (regulationType == "PiecewiseLinear") {
    if (psi > params$PsiStartClosing) {
      stomatalClosure <- 0
      regulFact <- 1
      regulFactPrime <- 0
    } else if (psi > params$PsiClose) {
      stomatalClosure <- 1
      regulFact <- (psi - params$PsiClose) / (params$PsiStartClosing - params$PsiClose)
      regulFactPrime <- 1 / (params$PsiStartClosing - params$PsiClose)
    } else {
      stomatalClosure <- 2
      regulFact <- 0
      regulFactPrime <- 0
    }
  } else if (regulationType == "Sigmoid") {
    stomatalClosure <- NA # stomatalClosure not relevant ofr sigmoid
    PL_gs <- 1 / (1 + exp(params$slope_gs / 25 * (psi - params$P50_gs)))
    regulFact <- 1 - PL_gs
    al <- params$slope_gs / 25
    regulFactPrime <- al * PL_gs * regulFact
    # regulFactPrime = al*exp(-al*(psi-P50_gs)) / ((1+exp(-al*(psi-P50_gs)))^2) # formulation in psi (same but slower to compute)
  } else if (regulationType == "Turgor") {
    stomatalClosure <- NA # stomatalClosure not relevant for Turgor
    rs <- Rs.Comp(PiFT = params$PiFullTurgor_Leaf, Esymp = params$epsilonSym_Leaf, Pmin = psi)
    turgor <- turgor.comp(PiFT = params$PiFullTurgor_Leaf, Esymp = params$epsilonSym_Leaf, Rstemp = rs)
    regulFact <- max(0, min(1, turgor / params$turgorPressureAtGsMax))
    #regulFact <- max(0, min(1, turgor / params$minTurgorAtGsMax))

    if (regulFact == 1 | regulFact == 0) {
      regulFactPrime <- 0
    } else {
      regulFactPrime <- 0 # TODO insert the derivative to compute regulFactPrime
    }
  }
  return(list("regulFact" = regulFact, "stomatalClosure" = stomatalClosure, "regulFactPrime" = regulFactPrime))
}


Here is the code

URFM, INRAe, Avignon
--


De : Erick Calderón-Morales ***@***.***>
Répondre à : NicoINRA/SurEau_V2 ***@***.***>
Date : mardi 12 décembre 2023 à 06:18
À : NicoINRA/SurEau_V2 ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [NicoINRA/SurEau_V2] Missing parameters in `regulfactTurgor.comp` function definition (Issue #3)


Hi Nico!

There are some missing parameters in the definition of the regulfactTurgor.comp function

The function is defined as:

regulfactTurgor.comp <- function(Tpress = Tpress, TpRESSUREMax = TpRESSUREMax)

however the Emax and Ecuti are missing.

I think the definition should be:

regulfactTurgor.comp <- function(Tpress, TpRESSUREMax, Emax, Ecuti)

since those are parameters that are required:

https://github.com/NicoINRA/SurEau_V2/blob/6c82eae48bce6ac1f7cb0722d8e2ef980f9d9fb1/functions/plant.utils.R#L66-L67

Best;
Erick
